### ISSUE TITLE
Failed installation after following Raspberry Pi instructions

### ISSUE THREAD

**Issue by CooperWhitlow** [museumsvictoria/nodel#113]
Nodel seems to install correctly and appears to be running, but after bringing up the web interface at localhost:8085, it cannot create nodes with the "Add new node" button nor display nodes created manually with "sudo mkdir /opt/nodel/nodes/TestNode."

Do I have to set some kind of permissions?

**Comment by scroix** [comment]
Hi @CooperWhitlow,

It does _sound_ like a permissions issue.

Try running another instance as superuser on a different port and see if the behavior persists.

`sudo java -jar nodel.jar -p 8086`

**Comment by CooperWhitlow** [comment]
Yes! Starting an instance with sudo like that allows it to work properly. Do you know how to allow the init.d script to run without sudo?

I tried change folder permissions of /opt/nodel without any luck.

**Comment by CooperWhitlow** [comment]
So I added ALL users to sudoers and the init.d nodel instance is now able to create new nodes but I see that it is creating them in /nodes, not /opt/nodel/nodes. This conflicts with the documentation.

**Comment by scroix** [comment]
I took a quick peak at the [Ubuntu Pre 15.04 ](https://github.com/museumsvictoria/nodel/wiki/Install-Nodel-as-an-init.d-%28Ubuntu-pre-15.04%29-Process) installation guide which the Raspberry Pi one was based off. There's a slight variation in the setup script that adds a current working directory to the Nodel launch script which should have the nodes being generated in /opt/nodel/nodes instead of /

`CWD="/opt/nodel"`
```
do_exec() {
    $EXEC -cwd $CWD -home $JAVA_HOME -cp $CLASS_PATH -pidfile $PID $CLASS
}

do_stop() {
    $EXEC -stop -cwd $CWD -home $JAVA_HOME -cp $CLASS_PATH -pidfile $PID $CLASS
}
```


This should help with the node location creation.

From memory, I believe you can install Nodel as a user instead, and leave it all in a home directory. The only trouble is that some recipes, such as the process management one is going to need full permissions.

Good luck!

**Comment by scroix** [comment]
Updated the wiki with an installer script based of @rhulse's script for Ubuntu 16.04

[https://gist.github.com/scroix/e820d66410e078f59d7757ddc6200835](https://gist.github.com/scroix/e820d66410e078f59d7757ddc6200835)
