### ISSUE TITLE
Support front-ends (index.xml) straight out-of-the-box

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#123]
Please see this recipe for what I believe is an ideal script and front-end combo - **[link to Yamaha Amp](https://github.com/museumsvictoria/nodel-recipes/tree/master/Yamaha%20XMV%20Series%20amplifier%20(ready%20for%20MTX3%2C%20MTX5-D%2C%20MRX7-D%2C%20EXi8%2C%20EXo8))**

Unfortunately, as it stands that does not work. Instead the front-end nodes all require an additional 24 files, totalling 2.63MB of scripts and binaries.

Managing all of that baggage each time is often cumbersome, if not impossible when being done via the web-browser.

Can any, or all of those dependencies get wrapped into the nodel release itself?

**Comment by mcartmel** [comment]
The reason this hasn't been moved into Nodel directly is because the Frontend recipe is quite different to the core Nodel interface and uses newer versions of libraries and build tools etc. There are a number of conflicts and it would be very messy.

Instead, the obvious solution is to update the Nodel interface to use the same environment as the Frontend recipe, then the old core interface can be removed and Frontend moved into the Nodel release. I've begun this task already, and I'm also working on some much needed improvements as well (like the binding ui).

**Comment by mcartmel** [comment]
The new UI now fully integrates the Frontend code, so only a simple 'index.xml' in the content folder of a recipe is required to include a frontend in the recipe. Closing this issue, but I will create some others to deal with the changes required to existing recipes to make them compatible.
