### ISSUE TITLE
Java moving to commercial licence 

### ISSUE THREAD

**Issue by Joe-Coleman1** [museumsvictoria/nodel#148]
When I install the Java runtime on a new computer I am getting a message that Java will be moving to a commercial license for corporate users from January 19. What's our position on this?

<img width="708" alt="screen shot 2018-12-20 at 11 53 40 am" src="https://user-images.githubusercontent.com/46013748/50261761-2a083d80-0462-11e9-9988-6af62756850f.png">

**Comment by justparking** [comment]
[OpenJDK](https://openjdk.java.net) should be fine.

Most of our Linux-based installs use OpenJDK already. I'll start using it more often on Windows from today.

Nodel is tested with Java 8, which they offer, but tag "early adopter release" even though it has been around for a very long time: [link](https://jdk.java.net/8/)

OpenJDK's latest is Java 11: [link](https://jdk.java.net/11/)

I've done very basic testing with Java 11. It spat out a few warnings that I've yet to follow up on, but things still seemed to work.

One difference between Oracle and OpenJDK (could be seen as a blessing) is they only support a "portable" install method meaning you download an archive and expand it.

And that download doesn't require any ticking of license boxes like you *have* to do with Oracle Java.
Means from zero-dependencies present, Nodel can be bootstrapped from something much smaller. A little EXE or BASH script that downloads OpenJava ("install-less"), downloads nodel and registers as a service for both Linux and Windows (with a few basic options of course).

**Comment by justparking** [comment]
**FYI: Nodel and differences between JRE and JDK**

The JRE is purely the runtime environment with minimal baggage.

The JDK is the JRE plus a few extra software development tools, one being a Java compiler.

Nodel doesn't require the JDK, _however_ if you have the choice, download the JDK since it has functionality that may be used in future versions of Nodel or Nodel recipes.

**Comment by Joe-Coleman1** [comment]
I still can't get Nodel to run as a service with OpenJDK 11. I think that the Procure service wrapper might be the problem. Are there any plans to update the service wrapper to be compatible with newer versions of Open Java?

**Comment by scroix** [comment]
You should be okay if you launch Java through the use of the `jvm.dll` library.

![jvmservice](https://user-images.githubusercontent.com/9277107/53142449-03908b00-35e8-11e9-9661-d7f1e2c3ca62.PNG)

**Comment by justparking** [comment]
Even though it seems to run reasonably well on Java 11 (excluding a few unusual warnings on launch), very little long term testing has been done with Nodel on Java 11. Nodel was built and has only been thoroughly road tested with Java 8.

Because of this, I strongly encourage the use of Java 8 until Java 11 can be confidently endorsed for use with Nodel.

Java 11 and Java 8 are very different platforms more so than just different revisions of Java.

They are both offered with LTS (Long-Term-Supported) releases right up until similar times. For Java 8, until at least Sept 2023. For Java 11, at least Sept 2022 (see [here](https://adoptopenjdk.net/support.html)).

You can find well supported pre-built installation packages of Java 8 at https://adoptopenjdk.net/ (full installer or "portable" ZIP package can be downloaded).

We'll need to update the Nodel wiki to reflect the best place to download Java on Windows platforms.

@josejones From what I can tell there aren't at licensing restrictions that'd affect us if that build is used but you might want to confirm.

**Comment by justparking** [comment]
Installation instructions refer to Adopt JDK so this can be closed.
